#Counting DNA Nucleotide
DNA_sequence = "ACCCCAGCAGTAATGTCACGCATGAGCAATAATCGCGGCATCGTCCTGTTACTGTTGGCCAAACACCATCTATGTGTGAGGGGCGTCAGCATGGACAACTACAATGAACATCTACATGGGAACACTAATTCAGTTTACAAAGTGTAGGAGGGGACACGGAAGCCAGGATGATCCCTAGTAGGCACCCGAATCATGCTGCCAGTCCAATACACATAGCCGCTTTCTTTGGGATCGGTGACAGCACGGTCCAGTGCCACGTCGAATCGTCCAAACATTCAATCAGCCTTTGGCCCTCACACCAGAGTTATCGACTATTAGGTGCCCCGCATAAGATCCGGTCCGCGTCGTTGCGTAAAACAGAGAAGCGGAAGGTTTTCCACTTTGTTGTTCGCTTTGGCGAAAGCCTTCGTCACACCGTGTACTGATGTTTATCAGGACAACTAGCACGCTAGTCTAATTCGTGGTCACGCTTGGCCTCTCCAGTCCTAACAAAGTGCTACCGACGCTAGTCGTCCTGCGACGGGTGTATCCGTAATAGACGCTCATATACCAGACATTTCGATGGTCTGTCATTCCTGTAACCTGTAACAACACAAAGGCTTCGACTCTGTCGGGTGCGACGCACTTATAAATAACCCCTCTAAGATACTGCCGTTCCAAGCTGCTCCTTTTCAGCCGACGTTGAGGGAATTATAAAAAGGCACGGGCCGGCTCTGAACGAAGTACTTGAGATCCTTAAACAAACAAATGCTTCAGCTGCGGCAAGCCGCTCGACGCTGAACAAAACGACATATGGTGCTTTTAAACAGGCCGCCCGAGGTACTTCCTCAGCCCCACATCAGTCCACGCTGAACAGGGCCGATACGACTATTGTGTTGTTTCGGCCTGTAAGACAGGCAGCCCATGAAGAGTCCG"

#My solution
# using count() to get count
# counting A,C,G,T
counterA = DNA_sequence.count('A')
counterC = DNA_sequence.count('C')
counterG = DNA_sequence.count('G')
counterT = DNA_sequence.count('T')

# printing result
print("Count of A in DNA sequence is : "+ str(counterA))
print("Count of C in DNA sequence is : "+ str(counterC))
print("Count of G in DNA sequence is : "+ str(counterG))
print("Count of T in DNA sequence is : "+ str(counterT))
